### ISSUE TITLE
From where I can get those keys

### ISSUE THREAD

**Issue by Nes-cmd** [VP-Trading/telebirr-ussd#5]
Hello there, I want to develop USSD option after developing webcheckout following docs and credential given on dev-portal. But in this pachage the keys that listed in config are very different from what can I obtain from developer portal. Are all these provided from them even for test or its name difference from what are provided online, like Merchant AppId, Fabric App ID, App Secret, PrivateKey are provided online? 

Thanks for your help

**Comment by alazark94** [comment]
Hey you need to request the keys from Ethio telecom
